### ISSUE TITLE
Trying to install, but Dependency is not satisfiable

### ISSUE THREAD

**Issue by yratof** [geraldoramos/pigeon#11]
Running into this when trying to run `./pigeon_install.sh`

    Dependency is not satisfiable: libavcodec56 (>= 6:11~beta1)|libavcodec-extra-56 (>= 6:11.7)

Any ideas why it's not able to build or pass? Running latest rasperian

**Comment by geraldoramos** [comment]
Looks like the issue is related to motion installation:
https://github.com/Motion-Project/motion/issues/474

Looks like Motion is now part of the distribution and could be installed with:
sudo apt-get install motion

So, you may just edit the pigeon.sh file and replace it's content with the following (and try again):

```
CONF='pigeon.conf'
MODULES='pigeon_modules_init.sh'

echo "Starting Pigeon installation, please type your PI password when prompted" &&
echo "Updating..." &&
sudo apt-get update &&
sudo apt-get dist-upgrade &&
echo "Installing Motion detection software" &&
sudo apt-get install motion
echo "Motion installation completed" &&
sudo chmod +x pigeon_modules_init.sh &&
sudo ./pigeon_modules_init.sh install &&
echo -n "Please define a name for this Pigeon camera (ex: backyard):"
read camera_name
sudo sed -i -e "/camera_name=/s/.*/camera_name=$camera_name/" $MODULES &&
echo -n "Do you want to setup a password to access the live feed? [Y/n]:"
read password
if [[ $password == "y" ]] || [[ $password == "Y" ]] || [[ $password == "Yes" ]] || [[ $password == "yes" ]]
  then
    echo -n "Choose a login:"
    read login
    echo -n "Choose a password:"
    read passwd
    sudo sed -i -e "/stream_authentication/s/.*/stream_authentication $login:$passwd/" $CONF &&
    sudo sed -i -e "/stream_auth_method/s/.*/stream_auth_method 1/" $CONF
  fi
echo -n "Do you want to setup a different port (default is 8099) for the streaming server?[Y/n]"
read port
if [[ $port == "y" ]] || [[ $port == "Y" ]] || [[ $port == "Yes" ]] || [[ $port == "yes" ]]
  then
    echo -n "Choose a port (ex: 8033):"
    read finalport
    sudo sed -i -e "/stream_port/s/.*/stream_port $finalport/" $CONF
  else
  finalport=8099
  fi
sudo motion -c $CONF &&
echo "=========================="
echo "Installation completed and service started" &&
echo "You can add the following command to your 'rc.local' file to run on startup:" &&
echo 'motion -c /home/pi/pigeon/'$CONF
echo "-------------------------"
echo "You can now watch your live stream at:"
ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | { read ip; echo http://$ip:$finalport; }
echo "Please report any issues to github.com/geraldoramos/pigeon" &&
echo "=========================" &&
exit 1

```

Let me know if it works. I may update the file if it's the case.

**Comment by yratof** [comment]
I had noticed that I could install motion with just a simple apt-get install. Will try now to get around it & fire up pigeon. Will report back shortly

**Comment by yratof** [comment]
Ok. Everything installed and the whole script shot through installation. However, one line stuck out to me, and for this, there is no camera feed

`conf_cmdparse: unknown config option "mmalcam_name"`

And heading to the IP, this is the feed:

<img width="694" alt="screen shot 2017-08-25 at 10 21 34" src="https://user-images.githubusercontent.com/1001935/29705634-3ca57c78-897f-11e7-886e-b2af37d77083.png">

I'm wondering if there's a package possibly missing?

**Comment by yratof** [comment]
Ok, i've found the issue, it's with Motion/Jessie – This is the fix for the problem:

https://raspberrypi.stackexchange.com/questions/27737/unable-to-open-video-device-and-grey-screen

`sudo modprobe bcm2835-v4l2` needs to be run at some point to get the camera working with video feeds - the link shows that you can have this apart of motions boot process
