### ISSUE TITLE
Possible to swap dropbox for SFTP

### ISSUE THREAD

**Issue by yratof** [geraldoramos/pigeon#13]
> Your dropbox is full.
> Your dropbox is full.
> Your dropbox is full.
> Your dropbox is full.

Constant messages from the activity that's happening in these parts. I'd rather not pay for dropbox when there are cool projects like [nextcloud.com](https://nextcloud.com/) available.

Would you consider supporting a different option for storing photos? Nextcloud or sFTP?

**Comment by geraldoramos** [comment]
Hey there, that's good feedback. I will try to build other storage modules as soon as I can...
