### ISSUE TITLE
drive Usage

### ISSUE THREAD

**Issue by tomcom05** [geraldoramos/pigeon#8]
I am having an issue that causes all the SD card space to fill up on long records. Only fix I can find is to manually delete everything in the /home/pi/pigeon/motion_files directory.

Any way this can be an automated process?

**Comment by geraldoramos** [comment]
Is the dropbox integration working for you? This module is supposed to remove the file after uploading to Dropbox (either a picture or video). Can you please let me know the content of the /motion_files directory?

**Comment by tomcom05** [comment]
The dropbox integration is working and uploading content. The issue is it does not always seem to remove the content from the /motion_files directory if a file gets too long (prolonged motion). I then have to complete a manual delete to clean it up. 

The /motion_files directory has mp4 files in it as I have the picture saves turned off.

**Comment by geraldoramos** [comment]
A possible solution could be to add a line like this at the end of the **on_movie_end.sh** file for the dropbox module:

`sudo find /home/pi/pigeon/motion_files/ -mindepth 1 -mtime +2 -delete`

"mtime +2" will delete any file older than 2 days (you can change to whatever time you feel comfortable deleting. This way, for every new movie added, it will make sure other movies older than X days will be removed in the same routine.

More info about the command:  https://unix.stackexchange.com/questions/194863/delete-files-older-than-x-days

I will confirm this is happening to me as well, I'm using Pigeon for a long time and didn't have the problem, but I rarely have long motions.

**Comment by tomcom05** [comment]
Sorry for my late response.

I just made this change on my end to all three of my pigeon cams and will let you know what i see after a few days.

Thanks,
Tom

**Comment by tomcom05** [comment]
That change resolved the issue.

Thanks!
