### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by richardhughes260** [geraldoramos/pigeon#9]
Any thoughts on an outdoor waterproof case? Maybe adding a groove for a n"O" ring & closing up the ports.

Any way to do a fisheye lens or kits for that out there?

I really like having a security cam that I have root on!!!

**Comment by geraldoramos** [comment]
Thanks for the feedback! I'm sorry, but I've been busy lately and didn't have much time to spend on this project. 

The O'ring idea is great, but what about the cords(power) opening? That part might need epoxy or something to seal it after connecting the power cord to the micro-USB port.

I can share the 3D source code with you if you want. It has been designed using Onshape, If you have an account there, you can send me the username, and I will share with you.

I will try to get back to this project at some point. There are so much I would like to do and looks like a decent amount of people are using.

It would be great to have contributors, but I couldn't find anyone so far.
